apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hakongo-connector-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "persistentvolumes", "namespaces", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["hakongo.io"]
  resources: ["connectorconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["hakongo.io"]
  resources: ["connectorconfigs/status"]
  verbs: ["get", "update", "patch"]
