apiVersion: hakongo.hakongo.com/v1alpha1
kind: ConnectorConfig
metadata:
  name: connectorconfig-sample
spec:
  hakongo:
    baseUrl: "http://localhost:3000"
    clusterId: "prod-us-west-2"
    apiKeySecret:
      name: hakongo-api-key
      key: api-key

  clusterContext:
    name: "production-cluster"
    providerName: "aws"
    region: "us-west-2"
    zone: "us-west-2a"
    labels:
      environment: "production"
      team: "platform"
      cost-center: "12345"
    metadata:
      vpc_id: "vpc-1234567890abcdef0"
      subnet_ids: ["subnet-abc123", "subnet-def456"]

  collectors:
    - name: "pod"
      enabled: true
    - name: "node"
      enabled: true
    - name: "pv"
      enabled: true
    - name: "service"
      enabled: true
    - name: "namespace"
      enabled: true
    - name: "workload"
      enabled: true
    - name: "ingress"
      enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: hakongo-api-key
type: Opaque
data:
  api-key: dGVzdC1hcGkta2V5  # This is "test-api-key" in base64
