apiVersion: hakongo.com/v1alpha1
kind: ConnectorConfig
metadata:
  name: connector-sample
spec:
  hakongo:
    # Use our mock API server running in the cluster
    baseURL: "http://mock-hakongo-api.default.svc.cluster.local"
    apiKey:
      name: hakongo-api-key
      key: api-key

  clusterContext:
    name: "my-cluster"
    type: "kind"
    region: "local"
    labels:
      environment: "development"
      team: "platform"
    metadata:
      provider: "docker-desktop"

  # Prometheus configuration - primary metrics source
  prometheus:
    url: "http://my-kube-prometheus-stack-prometheus.default.svc.cluster.local:9090"
    scrapeInterval: "30s"
    queryTimeout: "30s"
    serviceMonitorSelector:
      release: "my-kube-prometheus-stack"
      
  # Metrics Server configuration - fallback metrics source
  metricsServer:
    enabled: true

  collectors:
    - name: "pod"
      interval: 60
      labels:
        environment: "development"
        cluster_type: "docker-desktop"
    - name: "node"
      interval: 60
    - name: "pv"
      interval: 120
    - name: "service"
      interval: 120
    - name: "namespace"
      interval: 300
      labels:
        collector: "namespace"
    - name: "workload"
      interval: 300
      labels:
        collector: "workload"
    - name: "ingress"
      interval: 300
      labels:
        collector: "network"
---
apiVersion: v1
kind: Secret
metadata:
  name: hakongo-api-key
type: Opaque
data:
  api-key: b3JnXzEtNmViMWE1ZTRhZjc2N2Y1ZTg2ZDBkNmIxMTYyMmRkOWM=  # Base64 encoded API key
